name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - uses: actions/upload-artifact@master
      with:
        name: code
        path: .

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    needs:
    - checkout

    steps:
    - uses: actions/download-artifact@master
      with:
        name: code
        path: .

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - uses: actions/upload-artifact@master
      with:
        name: executable
        path: jwtproxy

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.13
    needs: 
    - checkout
    
    steps:
    - uses: actions/download-artifact@master
      with:
        name: code
        path: .

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: go test -v .

  docker:
    name: docker
    runs-on: ubuntu-latest
    needs: 
    - build

    steps:
    - uses: actions/download-artifact@master
      with:
        name: code
        path: .
    - uses: actions/download-artifact@master
      with:
        name: executable
        path: jwtproxy
    - run: docker build .
